"""Bundle the app into pawpal-standalone.html.

The five source files stay separate for editing. This folds them into one
self-contained document that can be emailed, copied to a USB stick or opened
from a Downloads folder without its siblings.

    python build.py
"""

import io

SOURCES = ('fonts.css', 'styles.css', 'motion.css')
OUT = 'pawpal-standalone.html'

HEADER = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PawPal</title>
<!--
  PawPal, single file.
  Everything the app needs is inside this one document: markup, styles,
  animations, script and both typefaces. Nothing is loaded from anywhere.
  Copy it anywhere, open it in any browser, works with no internet.
  Edit the separate files in the repo, not this one; it is generated by build.py.
-->
<style>
"""


def main():
    html = io.open('index.html', encoding='utf-8').read()
    css = ''.join(io.open(f, encoding='utf-8').read() for f in SOURCES)
    js = io.open('app.js', encoding='utf-8').read()

    body = html.split('<body>', 1)[1].rsplit('</body>', 1)[0]
    body = body.replace('<script src="app.js"></script>', '')

    out = HEADER + css + '\n</style>\n</head>\n<body>\n' + body \
        + '\n<script>\n' + js + '\n</script>\n</body>\n</html>\n'

    io.open(OUT, 'w', encoding='utf-8').write(out)
    print('%s written, %.2f MB' % (OUT, len(out.encode('utf-8')) / 1048576.0))


if __name__ == '__main__':
    main()
